In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('D:\CuratioFlow\data\emotion-emotion_69k.csv')

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 10000)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Debjit\AppData\Local\Temp\ipykernel_26296\3535807466.py:1: SyntaxWarning: invalid escape sequence '\C'
  data = pd.read_csv('D:\CuratioFlow\data\emotion-emotion_69k.csv')

In [4]:
from datasets import load_dataset

# Amod - real counselor Q&A conversations
amod_ds = load_dataset("Amod/mental_health_counseling_conversations", split="train")

# SohamGhadge - casual conversation tone
soham_ds = load_dataset("SohamGhadge/casual-conversation", split="train")

d:\CuratioFlow\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
data.head()

   Unnamed: 0                                          Situation      emotion                               empathetic_dialogues                                             labels Unnamed: 5 Unnamed: 6
0           0  I remember going to the fireworks with my best...  sentimental  Customer :I remember going to see the firework...  Was this a friend you were in love with, or ju...        NaN        NaN
1           1  I remember going to the fireworks with my best...  sentimental  Customer :This was a best friend. I miss her.\...                                Where has she gone?        NaN        NaN
2           2  I remember going to the fireworks with my best...  sentimental              Customer :We no longer talk.\nAgent :  Oh was this something that happened because of...        NaN        NaN
3           3  I remember going to the fireworks with my best...  sentimental  Customer :Was this a friend you were in love w...                This was a best friend. I miss her.        NaN        NaN
4           4  I remember going to the fireworks with my best...  sentimental             Customer :Where has she gone?\nAgent :                                 We no longer talk.        NaN        NaN

In [6]:
data = data[['Situation','empathetic_dialogues','labels']]

In [7]:
data.head(10)

                                           Situation                               empathetic_dialogues                                             labels
0  I remember going to the fireworks with my best...  Customer :I remember going to see the firework...  Was this a friend you were in love with, or ju...
1  I remember going to the fireworks with my best...  Customer :This was a best friend. I miss her.\...                                Where has she gone?
2  I remember going to the fireworks with my best...              Customer :We no longer talk.\nAgent :  Oh was this something that happened because of...
3  I remember going to the fireworks with my best...  Customer :Was this a friend you were in love w...                This was a best friend. I miss her.
4  I remember going to the fireworks with my best...             Customer :Where has she gone?\nAgent :                                 We no longer talk.
5                       i used to scare for darkness  Customer : it feels like hitting to blank wall...                      Oh ya? I don't really see how
6                       i used to scare for darkness  Customer :dont you feel so.. its a wonder \nAg...  I do actually hit blank walls a lot of times b...
7                       i used to scare for darkness  Customer : i virtually thought so.. and i used...                            Wait what are sweatings
8                       i used to scare for darkness   Customer :Oh ya? I don't really see how\nAgent :                   dont you feel so.. its a wonder
9                       i used to scare for darkness  Customer :I do actually hit blank walls a lot ...   i virtually thought so.. and i used to get sw...

In [8]:
data.duplicated().sum()

np.int64(13)

In [9]:
data = data.drop_duplicates()

In [10]:
len(data)

64623

In [11]:
print(data['empathetic_dialogues'][2])

Customer :We no longer talk.
Agent :

In [12]:
print(data['labels'][2])

Oh was this something that happened because of an argument?

In [13]:
def rev_extra(txt):
    new_txt = ''
    for c in txt.split():
        if c == 'Customer' or c == ':' or c == 'Agent': continue
        else: new_txt = new_txt + c + " "

    return new_txt[1:]

print(rev_extra('Customer :I remember going to see the fireworks with my best friend. It was the first time we ever spent time alone together. Although there was a lot of people, we felt like the only people in the world. Agent :'))

I remember going to see the fireworks with my best friend. It was the first time we ever spent time alone together. Although there was a lot of people, we felt like the only people in the world.

In [14]:
data['empathetic_dialogues'] = data['empathetic_dialogues'].apply(rev_extra)

In [15]:
len(data)

64623

In [16]:
data.head()

                                           Situation                               empathetic_dialogues                                             labels
0  I remember going to the fireworks with my best...  I remember going to see the fireworks with my ...  Was this a friend you were in love with, or ju...
1  I remember going to the fireworks with my best...               This was a best friend. I miss her.                                 Where has she gone?
2  I remember going to the fireworks with my best...                                We no longer talk.   Oh was this something that happened because of...
3  I remember going to the fireworks with my best...  Was this a friend you were in love with, or ju...                This was a best friend. I miss her.
4  I remember going to the fireworks with my best...                               Where has she gone?                                  We no longer talk.

In [17]:
amod_df = amod_ds.to_pandas()
soham_df = soham_ds.to_pandas()

In [18]:
amod_df['Context'].duplicated().sum()

np.int64(2517)

In [19]:
amod_df = amod_df.drop_duplicates()

In [20]:
amod_df.head()

                                             Context                                           Response
0  I'm going through some things with my feelings...  If everyone thinks you're worthless, then mayb...
1  I'm going through some things with my feelings...  Hello, and thank you for your question and see...
2  I'm going through some things with my feelings...  First thing I'd suggest is getting the sleep y...
3  I'm going through some things with my feelings...  Therapy is essential for those that are feelin...
4  I'm going through some things with my feelings...  I first want to let you know that you are not ...

In [21]:
len(amod_df)

2752

In [22]:
soham_df = soham_df[['question','answer']]

In [23]:
soham_df.head()

                              question                                    answer
0               hi, how are you doing?             i'm fine. how about yourself?
1        i'm fine. how about yourself?       i'm pretty good. thanks for asking.
2  i'm pretty good. thanks for asking.         no problem. so how have you been?
3    no problem. so how have you been?          i've been great. what about you?
4     i've been great. what about you?  i've been good. i'm in school right now.

In [24]:
len(soham_df)

3725

In [25]:
soham_df.duplicated().sum()

np.int64(1)

In [26]:
soham_df = soham_df.drop_duplicates()

In [27]:
soham_df = soham_df.iloc[:len(amod_df)]

In [28]:
len(soham_df)

2752

In [29]:
data = data[:5504]

In [30]:
data = data[['empathetic_dialogues','labels']]

In [31]:
data.rename(columns={'empathetic_dialogues': 'question', 'labels': 'answer'}, inplace=True)
amod_df.rename(columns={'Context': 'question', 'Response': 'answer'}, inplace=True)

In [32]:
len(data)

5504

In [33]:
combined = pd.concat([data, amod_df], axis=0, ignore_index=True)
combined = pd.concat([combined, soham_df], axis=0, ignore_index=True)
len(combined)

11008

In [34]:
combined.head(20)

                                             question                                             answer
0   I remember going to see the fireworks with my ...  Was this a friend you were in love with, or ju...
1                This was a best friend. I miss her.                                 Where has she gone?
2                                 We no longer talk.   Oh was this something that happened because of...
3   Was this a friend you were in love with, or ju...                This was a best friend. I miss her.
4                                Where has she gone?                                  We no longer talk.
5   t feels like hitting to blank wall when i see ...                      Oh ya? I don't really see how
6                    dont you feel so.. its a wonder   I do actually hit blank walls a lot of times b...
7    virtually thought so.. and i used to get swea...                            Wait what are sweatings
8                      Oh ya? I don't really see how                    dont you feel so.. its a wonder
9   I do actually hit blank walls a lot of times b...   i virtually thought so.. and i used to get sw...
10                        Hi how are you doing today                          doing good.. how about you
11  Im good, trying to understand how someone can ...       it's quite strange that you didnt imagine it
12                        doing good.. how about you   Im good, trying to understand how someone can ...
13      it's quite strange that you didnt imagine it   i dont imagine feeling a lot, maybe your on to...
14                  I have never cheated on my wife.   And thats something you should never do, good ...
15  Yea it hasn't been easy but I am proud I haven't   What do you mean it hasn't been easy? How clos...
16  And thats something you should never do, good ...   Yea it hasn't been easy but I am proud I haven't
17  Job interviews always make me sweat bullets, m...                Don't be nervous. Just be prepared.
18  I feel like getting prepared and then having a...            Yes but if you stay calm it will be ok.
19               Don't be nervous. Just be prepared.   I feel like getting prepared and then having a...

In [36]:
combined.to_csv('D:\CuratioFlow\data\data.csv',index=False)

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Debjit\AppData\Local\Temp\ipykernel_26296\3041565675.py:1: SyntaxWarning: invalid escape sequence '\C'
  combined.to_csv('D:\CuratioFlow\data\data.csv',index=False)